import { type Metadata } from 'next'
import { Noto_Sans, SUSE } from 'next/font/google'

import './globals.scss'

const notoSans = Noto_Sans({
	variable: '--font-noto-sans',
	subsets: ['latin'],
	display: 'swap',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

const suse = SUSE({
	variable: '--font-suse',
	subsets: ['latin'],
	display: 'swap',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${notoSans.variable} ${suse.variable} antialiased`}>{children}</body>
		</html>
	)
}
